"""
===============================================================================
Universal Prompt Studio
Engineering Toolkit

Markdown Renderer

This module renders documentation models into deterministic, structured
Markdown output. The renderer is responsible for formatting only; it does
not access project sources or perform analysis.

All output is UTF-8 encoded and deterministic given the same input model.

Public API
----------
from Engineering.Documentation.renderer import MarkdownRenderer

renderer = MarkdownRenderer()
markdown = renderer.render_document(document)

===============================================================================
"""

from __future__ import annotations

from Engineering.core.constants import ENGINEERING_NAME, PROJECT_NAME
from Engineering.core.version import VERSION

from .models import (
    DocumentationDocument,
    DocumentationElement,
    DocumentationElementKind,
    DocumentationSection,
)
from .readers import StructureNode

__all__ = ["MarkdownRenderer"]


# -----------------------------------------------------------------------------
# Auto-Generated Header
# -----------------------------------------------------------------------------


def _auto_generated_header(source: str = "") -> str:
    """
    Return the standard auto-generated document header.
    """

    source_line = ""
    if source:
        source_line = f"\nSource: {source}"

    return (
        "<!--\n"
        "===============================================================================\n"
        "AUTO-GENERATED FILE\n"
        f"Generated by {PROJECT_NAME} {ENGINEERING_NAME} v{VERSION}.\n"
        "\n"
        "DO NOT EDIT MANUALLY.\n"
        f"{source_line}\n"
        "===============================================================================\n"
        "-->"
    )


# -----------------------------------------------------------------------------
# Markdown Renderer
# -----------------------------------------------------------------------------


class MarkdownRenderer:
    """
    Renders documentation models into Markdown strings.

    Output is deterministic: the same model always produces the same
    Markdown string, with no timestamps or environment-specific values.
    """

    def render_document(self, document: DocumentationDocument) -> str:
        """
        Render a complete documentation document to Markdown.

        Parameters
        ----------
        document
            The documentation document to render.

        Returns
        -------
        str
            Rendered Markdown content.
        """

        source = ""
        if document.metadata:
            source = document.metadata.source or document.metadata.generated_from

        lines: list[str] = []
        lines.append(_auto_generated_header(source))
        lines.append("")
        lines.append(f"# {document.title}")
        lines.append("")

        if document.description:
            lines.append(document.description)
            lines.append("")

        for section in document.sections:
            lines.append(self._render_section(section))
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    def _render_section(self, section: DocumentationSection) -> str:
        """
        Render a documentation section to Markdown.
        """


        lines: list[str] = []
        lines.append(f"{'#' * section.level} {section.title}")
        lines.append("")

        for element in section.elements:
            rendered = self._render_element(element)
            if rendered is not None:
                lines.append(rendered)
                lines.append("")

        return "\n".join(lines)

    def _render_element(self, element: DocumentationElement) -> str | None:
        """
        Render a single documentation element to Markdown.
        """

        kind = element.kind

        if kind == DocumentationElementKind.HEADING:
            return f"{'#' * element.level} {element.content}"

        if kind == DocumentationElementKind.PARAGRAPH:
            return element.content

        if kind == DocumentationElementKind.CODE_BLOCK:
            language = element.content.split("\n", 1)[0] if "\n" in element.content else ""
            code = element.content
            if language:
                code = element.content.split("\n", 1)[1] if "\n" in element.content else ""
            else:
                language = ""
            if language:
                return f"```{language}\n{code}\n```"
            return f"```\n{element.content}\n```"

        if kind == DocumentationElementKind.LIST:
            items = "\n".join(f"- {item}" for item in element.items)
            return items

        if kind == DocumentationElementKind.TABLE:
            return self._render_table(element.columns, element.rows)

        if kind == DocumentationElementKind.LINK:
            if element.items:
                return f"- [{element.content}]({element.items[0]})"
            return f"- {element.content}"

        if kind == DocumentationElementKind.SEPARATOR:
            return "---"

        return None

    def _render_table(
        self,
        columns: tuple[str, ...],
        rows: tuple[tuple[str, ...], ...],
    ) -> str:
        """
        Render a Markdown table.
        """

        if not columns:
            return ""

        header = " | ".join(columns)
        separator = " | ".join("---" for _ in columns)
        lines = [f"| {header} |", f"| {separator} |"]

        for row in rows:
            padded = list(row) + [""] * (len(columns) - len(row))
            line = " | ".join(padded[: len(columns)])
            lines.append(f"| {line} |")

        return "\n".join(lines)

    def render_tree(self, node: StructureNode) -> str:
        """
        Render a project structure tree to text lines.

        The root node is rendered without a connector. Child nodes use
        standard tree characters. Directories are sorted before files
        and all entries are sorted case-insensitively, so the output is
        deterministic.
        """

        lines: list[str] = []
        self._render_tree_node(node, lines, prefix="", is_last=True, is_root=True)
        return "\n".join(lines)

    def _render_tree_node(
        self,
        node: StructureNode,
        lines: list[str],
        prefix: str,
        is_last: bool,
        is_root: bool,
    ) -> None:
        """
        Recursively render a tree node.
        """

        name_display = f"{node.name}/" if node.is_directory else node.name

        if is_root:
            lines.append(name_display)
            child_prefix = ""
        else:
            connector = "└── " if is_last else "├── "
            lines.append(f"{prefix}{connector}{name_display}")
            child_prefix = prefix + ("    " if is_last else "│   ")

        if node.children:
            for i, child in enumerate(node.children):
                is_child_last = i == len(node.children) - 1
                self._render_tree_node(child, lines, child_prefix, is_child_last, False)
