"""E-015.6 controlled catalog-to-frontend transport tests."""

from __future__ import annotations

import os
from pathlib import Path

import pytest
from typer.testing import CliRunner

from Engineering.cli.app import app
from Engineering.core.exceptions import ThemeError
from Engineering.ThemeSystem import (
    FRONTEND_THEME_CATALOG_PATH,
    FRONTEND_THEME_CATALOG_SCHEMA_VERSION,
    ThemeAppearance,
    ThemeCatalog,
    ThemeFrontendCatalog,
    ThemeFrontendCatalogCompiler,
    ThemeFrontendCatalogSerializer,
    ThemeFrontendCatalogSynchronizer,
    ThemeService,
    ThemeTokenName,
)


def _project_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _catalog() -> ThemeCatalog:
    return ThemeService().catalog(_project_root() / "Themes")


def test_compiles_every_catalog_palette_in_stable_identity_order() -> None:
    result = ThemeFrontendCatalogCompiler().compile(_catalog())

    assert result.schema_version == FRONTEND_THEME_CATALOG_SCHEMA_VERSION
    assert tuple(
        (
            item.theme_id.value,
            item.version.value,
            item.appearance.value,
        )
        for item in result.selections
    ) == (
        ("ups.built-in", "1.0.0", "dark"),
        ("ups.built-in", "1.0.0", "high-contrast"),
        ("ups.built-in", "1.0.0", "light"),
    )
    assert all(
        tuple(token.name for token in item.tokens) == tuple(ThemeTokenName)
        for item in result.selections
    )


def test_serializer_is_deterministic_and_contains_data_only_module() -> None:
    document = ThemeFrontendCatalogCompiler().compile(_catalog())
    serializer = ThemeFrontendCatalogSerializer()

    first = serializer.serialize(document)
    second = serializer.serialize(document)

    assert first == second
    assert first.startswith("// AUTO-GENERATED by E-015.6")
    assert first.endswith("export default themeCatalog;\n")
    assert '"themeId": "ups.built-in"' in first
    assert '"appearance": "high-contrast"' in first
    assert "url(" not in first.lower()
    assert "<script" not in first.lower()


def test_tracked_frontend_module_exactly_matches_validated_catalog() -> None:
    expected = ThemeFrontendCatalogSerializer().serialize(
        ThemeFrontendCatalogCompiler().compile(_catalog())
    )
    tracked = (_project_root() / FRONTEND_THEME_CATALOG_PATH).read_text(
        encoding="utf-8"
    )

    assert tracked == expected


def test_synchronizer_writes_checks_and_preserves_current_file(tmp_path: Path) -> None:
    service = ThemeFrontendCatalogSynchronizer()

    first = service.synchronize(tmp_path, _catalog())
    target = tmp_path / FRONTEND_THEME_CATALOG_PATH
    original = target.read_bytes()
    timestamp = target.stat().st_mtime_ns
    second = service.synchronize(tmp_path, _catalog())
    checked = service.synchronize(tmp_path, _catalog(), check=True)

    assert first.current and first.changed
    assert first.selection_count == 3
    assert second.current and not second.changed
    assert checked.current and not checked.changed
    assert target.read_bytes() == original
    assert target.stat().st_mtime_ns == timestamp


def test_check_mode_reports_stale_without_writing(tmp_path: Path) -> None:
    target = tmp_path / FRONTEND_THEME_CATALOG_PATH
    target.parent.mkdir(parents=True)
    target.write_text("stale\n", encoding="utf-8")

    result = ThemeFrontendCatalogSynchronizer().synchronize(
        tmp_path,
        _catalog(),
        check=True,
    )

    assert not result.current
    assert not result.changed
    assert target.read_text(encoding="utf-8") == "stale\n"


def test_synchronizer_rejects_symlinked_and_oversized_targets(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    target = tmp_path / FRONTEND_THEME_CATALOG_PATH
    target.parent.mkdir(parents=True)
    original_is_symlink = Path.is_symlink

    def report_generated_as_symlink(path: Path) -> bool:
        return path.name == "generated" or original_is_symlink(path)

    monkeypatch.setattr(Path, "is_symlink", report_generated_as_symlink)
    with pytest.raises(ThemeError, match="must not contain symlinks"):
        ThemeFrontendCatalogSynchronizer().synchronize(tmp_path, _catalog())

    monkeypatch.setattr(Path, "is_symlink", original_is_symlink)
    target.write_bytes(b"x" * 1_000_001)
    with pytest.raises(ThemeError, match="size limit"):
        ThemeFrontendCatalogSynchronizer().synchronize(
            tmp_path,
            _catalog(),
            check=True,
        )


def test_failed_atomic_replace_leaves_no_temporary_file(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    def fail_replace(source: object, destination: object) -> None:
        raise OSError("simulated replacement failure")

    monkeypatch.setattr(os, "replace", fail_replace)

    with pytest.raises(ThemeError, match="could not be synchronized"):
        ThemeFrontendCatalogSynchronizer().synchronize(tmp_path, _catalog())

    generated = tmp_path / FRONTEND_THEME_CATALOG_PATH.parent
    assert not tuple(generated.glob("*.tmp"))
    assert not (tmp_path / FRONTEND_THEME_CATALOG_PATH).exists()


def test_transport_rejects_empty_catalog_and_invalid_document() -> None:
    with pytest.raises(ThemeError, match="at least one selection"):
        ThemeFrontendCatalogCompiler().compile(ThemeCatalog())
    with pytest.raises(ThemeError, match="schema_version"):
        ThemeFrontendCatalog(2, ())
    with pytest.raises(ThemeError, match="requires ThemeCatalog"):
        ThemeFrontendCatalogCompiler().compile("catalog")  # type: ignore[arg-type]


def test_cli_checks_the_tracked_frontend_catalog_without_writes() -> None:
    runner = CliRunner()

    result = runner.invoke(
        app,
        ["theme", "sync-frontend", "--root", "Themes", "--check"],
    )

    assert result.exit_code == 0
    assert "Frontend theme catalog current" in result.output
    assert "Selections transported: 3" in result.output


def test_built_in_manifest_exposes_all_supported_appearances() -> None:
    record = _catalog().resolve("ups.built-in", "1.0.0")

    assert {palette.appearance for palette in record.manifest.palettes} == set(
        ThemeAppearance
    )
